version: "3"
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    command: mongod --smallfiles
    ports:
     - "27017:27017"
    volumes:
     - ./mongo:/data/db:Z
  hygieia-api:
    image: liatrio/hygieia-api:2.0.5-theia-latest
    container_name: hygieia-api
    ports:
    - "8080:8080"
    volumes:
    - ./logs:/hygieia/logs:Z
    - ./properties:/hygieia/properties:Z
    links:
    - mongodb:mongo
